# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = ../../../.././newlib/libm/mathfp
top_srcdir = ../../../.././newlib/libm
VPATH = ../../../.././newlib/libm/mathfp
prefix = /usr/local/openxdk
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/newlib
pkglibdir = $(libdir)/newlib
pkgincludedir = $(includedir)/newlib

top_builddir = ..

ACLOCAL = aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,^,i386-pc-xbox-,;

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-cygwin
build_triplet = i686-pc-cygwin
host_alias = i386-pc-xbox
host_triplet = i386-pc-xbox
target_alias = i386-pc-xbox
target_triplet = i386-pc-xbox
AR = i386-pc-xbox-ar
AS = i386-pc-xbox-as
CC = i386-pc-xbox-gcc -B/cygdrive/c/source/workspaceEclipse/OpenXDK/src/newlib-1.12.0/i386-pc-xbox/newlib/ -isystem /cygdrive/c/source/workspaceEclipse/OpenXDK/src/newlib-1.12.0/i386-pc-xbox/newlib/targ-include -isystem /cygdrive/c/source/workspaceEclipse/OpenXDK/src/newlib-1.12.0/newlib/libc/include
CPP = @CPP@
CXX = @CXX@
CXXCPP = @CXXCPP@
DLLTOOL = i386-pc-xbox-dlltool
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
LDFLAGS = 
LIBM_MACHINE_LIB = machine/lib.a
LIBTOOL = 
LN_S = 
MAINT = #
MAKEINFO = makeinfo
NEWLIB_CFLAGS =  -O2 -D_COMPILING_NEWLIB -mno-cygwin -DMISSING_SYSCALL_NAMES -fno-builtin
OBJDUMP = 
OBJEXT = o
PACKAGE = newlib
RANLIB = i386-pc-xbox-ranlib
STRIP = 
VERSION = 1.12.0
aext = a
libm_machine_dir = i386
machine_dir = i386
newlib_basedir = ../../.././newlib/libm/..
oext = o
sys_dir = xbox

AUTOMAKE_OPTIONS = cygnus

INCLUDES = -I$(srcdir)/../common $(NEWLIB_CFLAGS) $(CROSS_CFLAGS) $(TARGET_CFLAGS)

src = s_acos.c s_frexp.c s_mathcnst.c 	s_cos.c s_sinh.c 	s_asin.c 	s_asine.c s_cosh.c s_ispos.c s_numtest.c s_sqrt.c 	s_exp.c s_ldexp.c s_pow.c s_tan.c 	s_atan.c 	s_atan2.c s_fabs.c s_log.c s_tanh.c 	s_log10.c s_sin.c 	s_floor.c s_sine.c 	s_sincos.c 	s_atangent.c s_logarithm.c 	s_sineh.c 	s_ceil.c s_isnan.c s_isinf.c 	e_acosh.c e_atanh.c e_remainder.c 	er_gamma.c er_lgamma.c 	s_erf.c e_j0.c e_j1.c w_jn.c e_hypot.c 	w_cabs.c w_drem.c s_asinh.c s_fmod.c 	e_scalb.c s_infconst.c s_signif.c 	s_exp2.c s_tgamma.c


fsrc = sf_ceil.c 	sf_acos.c sf_frexp.c 	sf_cos.c sf_sinh.c 	sf_asine.c sf_cosh.c sf_ispos.c sf_numtest.c sf_sqrt.c 	sf_asin.c 	sf_exp.c sf_ldexp.c sf_pow.c sf_tan.c 	sf_atan2.c sf_fabs.c sf_tanh.c 	sf_atan.c sf_log10.c sf_sin.c 	sf_floor.c sf_sine.c 	sf_sincos.c 	sf_atangent.c sf_logarithm.c sf_sineh.c 	sf_log.c sf_sineh.c 	sf_isnan.c sf_isinf.c 	ef_acosh.c ef_atanh.c ef_remainder.c 	erf_gamma.c erf_lgamma.c 	sf_erf.c ef_j0.c ef_j1.c wf_jn.c ef_hypot.c 	wf_cabs.c wf_drem.c sf_asinh.c sf_fmod.c 	ef_scalb.c sf_signif.c 	sf_exp2.c sf_tgamma.c


libmathfp_la_LDFLAGS = -Xcompiler -nostdlib

#noinst_LTLIBRARIES = libmathfp.la
#libmathfp_la_SOURCES = $(src) $(fsrc)
#noinst_DATA = objectlist.awk.in
noinst_DATA = 
noinst_LIBRARIES = lib.a
lib_a_SOURCES = $(src) $(fsrc)

chobj = eacosh.def 	eatanh.def 	ehypot.def 	eremainder.def 	erlgamma.def 	sacos.def 	sasine.def 	sasinh.def 	satan.def 	satan2.def 	satangent.def 	scosh.def 	serf.def 	sexp.def 	sfabs.def 	sfloor.def 	sfmod.def 	sfrexp.def 	sisnan.def 	sldexp.def 	slog10.def 	slogarithm.def 	spow.def 	ssine.def 	ssineh.def 	ssqrt.def 	stan.def 	stanh.def 	wjn.def


SUFFIXES = .def

CHEW = ../../doc/makedoc -f $(srcdir)/../../doc/doc.str

TARGETDOC = ../tmp.texi

CLEANFILES = $(chobj) *.ref
mkinstalldirs = $(SHELL) $(top_srcdir)/../../mkinstalldirs
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(noinst_LIBRARIES)


DEFS =  -DPACKAGE=\"newlib\" -DVERSION=\"1.12.0\"  -I. -I$(srcdir) 
CPPFLAGS = -O2 -g -O2
LIBS = 
lib_a_LIBADD = 
lib_a_OBJECTS =  s_acos.$(OBJEXT) s_frexp.$(OBJEXT) \
s_mathcnst.$(OBJEXT) s_cos.$(OBJEXT) \
s_sinh.$(OBJEXT) s_asin.$(OBJEXT) s_asine.$(OBJEXT) \
s_cosh.$(OBJEXT) s_ispos.$(OBJEXT) \
s_numtest.$(OBJEXT) s_sqrt.$(OBJEXT) s_exp.$(OBJEXT) \
s_ldexp.$(OBJEXT) s_pow.$(OBJEXT) s_tan.$(OBJEXT) \
s_atan.$(OBJEXT) s_atan2.$(OBJEXT) s_fabs.$(OBJEXT) \
s_log.$(OBJEXT) s_tanh.$(OBJEXT) s_log10.$(OBJEXT) \
s_sin.$(OBJEXT) s_floor.$(OBJEXT) s_sine.$(OBJEXT) \
s_sincos.$(OBJEXT) s_atangent.$(OBJEXT) \
s_logarithm.$(OBJEXT) s_sineh.$(OBJEXT) \
s_ceil.$(OBJEXT) s_isnan.$(OBJEXT) s_isinf.$(OBJEXT) \
e_acosh.$(OBJEXT) e_atanh.$(OBJEXT) \
e_remainder.$(OBJEXT) er_gamma.$(OBJEXT) \
er_lgamma.$(OBJEXT) s_erf.$(OBJEXT) e_j0.$(OBJEXT) \
e_j1.$(OBJEXT) w_jn.$(OBJEXT) e_hypot.$(OBJEXT) \
w_cabs.$(OBJEXT) w_drem.$(OBJEXT) s_asinh.$(OBJEXT) \
s_fmod.$(OBJEXT) e_scalb.$(OBJEXT) \
s_infconst.$(OBJEXT) s_signif.$(OBJEXT) \
s_exp2.$(OBJEXT) s_tgamma.$(OBJEXT) \
sf_ceil.$(OBJEXT) sf_acos.$(OBJEXT) \
sf_frexp.$(OBJEXT) sf_cos.$(OBJEXT) \
sf_sinh.$(OBJEXT) sf_asine.$(OBJEXT) \
sf_cosh.$(OBJEXT) sf_ispos.$(OBJEXT) \
sf_numtest.$(OBJEXT) sf_sqrt.$(OBJEXT) \
sf_asin.$(OBJEXT) sf_exp.$(OBJEXT) \
sf_ldexp.$(OBJEXT) sf_pow.$(OBJEXT) sf_tan.$(OBJEXT) \
sf_atan2.$(OBJEXT) sf_fabs.$(OBJEXT) \
sf_tanh.$(OBJEXT) sf_atan.$(OBJEXT) \
sf_log10.$(OBJEXT) sf_sin.$(OBJEXT) \
sf_floor.$(OBJEXT) sf_sine.$(OBJEXT) \
sf_sincos.$(OBJEXT) sf_atangent.$(OBJEXT) \
sf_logarithm.$(OBJEXT) sf_sineh.$(OBJEXT) \
sf_log.$(OBJEXT) sf_sineh.$(OBJEXT) \
sf_isnan.$(OBJEXT) sf_isinf.$(OBJEXT) \
ef_acosh.$(OBJEXT) ef_atanh.$(OBJEXT) \
ef_remainder.$(OBJEXT) erf_gamma.$(OBJEXT) \
erf_lgamma.$(OBJEXT) sf_erf.$(OBJEXT) \
ef_j0.$(OBJEXT) ef_j1.$(OBJEXT) wf_jn.$(OBJEXT) \
ef_hypot.$(OBJEXT) wf_cabs.$(OBJEXT) \
wf_drem.$(OBJEXT) sf_asinh.$(OBJEXT) \
sf_fmod.$(OBJEXT) ef_scalb.$(OBJEXT) \
sf_signif.$(OBJEXT) sf_exp2.$(OBJEXT) \
sf_tgamma.$(OBJEXT)
LTLIBRARIES =  $(noinst_LTLIBRARIES)

libmathfp_la_LIBADD = 
#libmathfp_la_OBJECTS =  s_acos.lo s_frexp.lo \
#s_mathcnst.lo s_cos.lo s_sinh.lo s_asin.lo s_asine.lo \
#s_cosh.lo s_ispos.lo s_numtest.lo s_sqrt.lo s_exp.lo \
#s_ldexp.lo s_pow.lo s_tan.lo s_atan.lo s_atan2.lo \
#s_fabs.lo s_log.lo s_tanh.lo s_log10.lo s_sin.lo \
#s_floor.lo s_sine.lo s_sincos.lo s_atangent.lo \
#s_logarithm.lo s_sineh.lo s_ceil.lo s_isnan.lo \
#s_isinf.lo e_acosh.lo e_atanh.lo e_remainder.lo \
#er_gamma.lo er_lgamma.lo s_erf.lo e_j0.lo e_j1.lo \
#w_jn.lo e_hypot.lo w_cabs.lo w_drem.lo s_asinh.lo \
#s_fmod.lo e_scalb.lo s_infconst.lo s_signif.lo \
#s_exp2.lo s_tgamma.lo sf_ceil.lo sf_acos.lo \
#sf_frexp.lo sf_cos.lo sf_sinh.lo sf_asine.lo \
#sf_cosh.lo sf_ispos.lo sf_numtest.lo sf_sqrt.lo \
#sf_asin.lo sf_exp.lo sf_ldexp.lo sf_pow.lo sf_tan.lo \
#sf_atan2.lo sf_fabs.lo sf_tanh.lo sf_atan.lo \
#sf_log10.lo sf_sin.lo sf_floor.lo sf_sine.lo \
#sf_sincos.lo sf_atangent.lo sf_logarithm.lo \
#sf_sineh.lo sf_log.lo sf_sineh.lo sf_isnan.lo \
#sf_isinf.lo ef_acosh.lo ef_atanh.lo ef_remainder.lo \
#erf_gamma.lo erf_lgamma.lo sf_erf.lo ef_j0.lo \
#ef_j1.lo wf_jn.lo ef_hypot.lo wf_cabs.lo wf_drem.lo \
#sf_asinh.lo sf_fmod.lo ef_scalb.lo sf_signif.lo \
#sf_exp2.lo sf_tgamma.lo
CFLAGS = -O2 -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(noinst_DATA)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(lib_a_SOURCES) $(libmathfp_la_SOURCES)
OBJECTS = $(lib_a_OBJECTS) $(libmathfp_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .def .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(srcdir)/../../Makefile.shared
	cd $(top_srcdir) && $(AUTOMAKE) --cygnus mathfp/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLIBRARIES:

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

distclean-noinstLIBRARIES:

maintainer-clean-noinstLIBRARIES:

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

lib.a: $(lib_a_OBJECTS) $(lib_a_DEPENDENCIES)
	-rm -f lib.a
	$(AR) cru lib.a $(lib_a_OBJECTS) $(lib_a_LIBADD)
	$(RANLIB) lib.a

mostlyclean-noinstLTLIBRARIES:

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)

distclean-noinstLTLIBRARIES:

maintainer-clean-noinstLTLIBRARIES:

libmathfp.la: $(libmathfp_la_OBJECTS) $(libmathfp_la_DEPENDENCIES)
	$(LINK)  $(libmathfp_la_LDFLAGS) $(libmathfp_la_OBJECTS) $(libmathfp_la_LIBADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = mathfp

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am:
check: check-am
installcheck-am:
installcheck: installcheck-am
install-info-am: 
install-info: install-info-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(LTLIBRARIES) $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-noinstLTLIBRARIES \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
		clean-noinstLTLIBRARIES clean-tags clean-generic \
		mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstLIBRARIES distclean-compile \
		distclean-libtool distclean-noinstLTLIBRARIES \
		distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-noinstLTLIBRARIES \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool mostlyclean-noinstLTLIBRARIES \
distclean-noinstLTLIBRARIES clean-noinstLTLIBRARIES \
maintainer-clean-noinstLTLIBRARIES tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-info-am install-info \
install-exec-am install-exec install-data-am install-data install-am \
install uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


objectlist.awk.in: $(noinst_LTLIBRARIES)
	-rm -f objectlist.awk.in
	for i in `ls *.lo` ; \
	do \
	  echo $$i `pwd`/$$i >> objectlist.awk.in ; \
	done

.c.def:
	$(CHEW) < $< > $*.def 2> $*.ref
	touch stmp-def

doc: $(chobj)
	cat $(srcdir)/mathfp.tex >> $(TARGETDOC)

# Texinfo does not appear to support underscores in file names, so we
# name the .def files without underscores.

eacosh.def: e_acosh.c
	$(CHEW) < $(srcdir)/e_acosh.c >$@ 2>/dev/null
	touch stmp-def
eatanh.def: e_atanh.c
	$(CHEW) < $(srcdir)/e_atanh.c >$@ 2>/dev/null
	touch stmp-def
ehypot.def: e_hypot.c
	$(CHEW) < $(srcdir)/e_hypot.c >$@ 2>/dev/null
	touch stmp-def
eremainder.def: e_remainder.c
	$(CHEW) < $(srcdir)/e_remainder.c >$@ 2>/dev/null
	touch stmp-def
erlgamma.def: er_lgamma.c
	$(CHEW) < $(srcdir)/er_lgamma.c >$@ 2>/dev/null
	touch stmp-def
sacos.def: s_acos.c
	$(CHEW) < $(srcdir)/s_acos.c >$@ 2>/dev/null
	touch stmp-def
sasine.def: s_asine.c
	$(CHEW) < $(srcdir)/s_asine.c >$@ 2>/dev/null
	touch stmp-def
sasinh.def: s_asinh.c
	$(CHEW) < $(srcdir)/s_asinh.c >$@ 2>/dev/null
	touch stmp-def
satan.def: s_atan.c
	$(CHEW) < $(srcdir)/s_atan.c >$@ 2>/dev/null
	touch stmp-def
satan2.def: s_atan2.c
	$(CHEW) < $(srcdir)/s_atan2.c >$@ 2>/dev/null
	touch stmp-def
satangent.def: s_atangent.c
	$(CHEW) < $(srcdir)/s_atangent.c >$@ 2>/dev/null
	touch stmp-def
scosh.def: s_cosh.c
	$(CHEW) < $(srcdir)/s_cosh.c >$@ 2>/dev/null
	touch stmp-def
serf.def: s_erf.c
	$(CHEW) < $(srcdir)/s_erf.c >$@ 2>/dev/null
	touch stmp-def
sexp.def: s_exp.c
	$(CHEW) < $(srcdir)/s_exp.c >$@ 2>/dev/null
	touch stmp-def
sfabs.def: s_fabs.c
	$(CHEW) < $(srcdir)/s_fabs.c >$@ 2>/dev/null
	touch stmp-def
sfloor.def: s_floor.c
	$(CHEW) < $(srcdir)/s_floor.c >$@ 2>/dev/null
	touch stmp-def
sfmod.def: s_fmod.c
	$(CHEW) < $(srcdir)/s_fmod.c >$@ 2>/dev/null
	touch stmp-def
sfrexp.def: s_frexp.c
	$(CHEW) < $(srcdir)/s_frexp.c >$@ 2>/dev/null
	touch stmp-def
sisnan.def: s_isnan.c
	$(CHEW) < $(srcdir)/s_isnan.c >$@ 2>/dev/null
	touch stmp-def
sldexp.def: s_ldexp.c
	$(CHEW) < $(srcdir)/s_ldexp.c >$@ 2>/dev/null
	touch stmp-def
slog10.def: s_log10.c
	$(CHEW) < $(srcdir)/s_log10.c >$@ 2>/dev/null
	touch stmp-def
slogarithm.def: s_logarithm.c
	$(CHEW) < $(srcdir)/s_logarithm.c >$@ 2>/dev/null
	touch stmp-def
spow.def: s_pow.c
	$(CHEW) < $(srcdir)/s_pow.c >$@ 2>/dev/null
	touch stmp-def
ssine.def: s_sine.c
	$(CHEW) < $(srcdir)/s_sine.c >$@ 2>/dev/null
	touch stmp-def
ssineh.def: s_sineh.c
	$(CHEW) < $(srcdir)/s_sineh.c >$@ 2>/dev/null
	touch stmp-def
ssqrt.def: s_sqrt.c
	$(CHEW) < $(srcdir)/s_sqrt.c >$@ 2>/dev/null
	touch stmp-def
stan.def: s_tan.c
	$(CHEW) < $(srcdir)/s_tan.c >$@ 2>/dev/null
	touch stmp-def
stanh.def: s_tanh.c
	$(CHEW) < $(srcdir)/s_tanh.c >$@ 2>/dev/null
	touch stmp-def
wjn.def: w_jn.c
	$(CHEW) < $(srcdir)/w_jn.c >$@ 2>/dev/null
	touch stmp-def

# A partial dependency list.

$(lib_a_OBJECTS): $(srcdir)/../../libc/include/math.h $(srcdir)/../common/fdlibm.h

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
