# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = ../../../.././newlib/libm/math
top_srcdir = ../../../.././newlib/libm
VPATH = ../../../.././newlib/libm/math
prefix = /usr/local/openxdk
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/newlib
pkglibdir = $(libdir)/newlib
pkgincludedir = $(includedir)/newlib

top_builddir = ..

ACLOCAL = aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,^,i386-pc-xbox-,;

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_alias = i686-pc-cygwin
build_triplet = i686-pc-cygwin
host_alias = i386-pc-xbox
host_triplet = i386-pc-xbox
target_alias = i386-pc-xbox
target_triplet = i386-pc-xbox
AR = i386-pc-xbox-ar
AS = i386-pc-xbox-as
CC = i386-pc-xbox-gcc -B/cygdrive/c/source/workspaceEclipse/OpenXDK/src/newlib-1.12.0/i386-pc-xbox/newlib/ -isystem /cygdrive/c/source/workspaceEclipse/OpenXDK/src/newlib-1.12.0/i386-pc-xbox/newlib/targ-include -isystem /cygdrive/c/source/workspaceEclipse/OpenXDK/src/newlib-1.12.0/newlib/libc/include
CPP = @CPP@
CXX = @CXX@
CXXCPP = @CXXCPP@
DLLTOOL = i386-pc-xbox-dlltool
EXEEXT = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
LDFLAGS = 
LIBM_MACHINE_LIB = machine/lib.a
LIBTOOL = 
LN_S = 
MAINT = #
MAKEINFO = makeinfo
NEWLIB_CFLAGS =  -O2 -D_COMPILING_NEWLIB -mno-cygwin -DMISSING_SYSCALL_NAMES -fno-builtin
OBJDUMP = 
OBJEXT = o
PACKAGE = newlib
RANLIB = i386-pc-xbox-ranlib
STRIP = 
VERSION = 1.12.0
aext = a
libm_machine_dir = i386
machine_dir = i386
newlib_basedir = ../../.././newlib/libm/..
oext = o
sys_dir = xbox

AUTOMAKE_OPTIONS = cygnus

INCLUDES = -I$(srcdir)/../common $(NEWLIB_CFLAGS) $(CROSS_CFLAGS) $(TARGET_CFLAGS)

src = k_standard.c k_rem_pio2.c 	k_cos.c k_sin.c k_tan.c 	e_acos.c e_acosh.c e_asin.c e_atan2.c 	e_atanh.c e_cosh.c e_exp.c e_fmod.c 	er_gamma.c e_hypot.c e_j0.c 	e_j1.c e_jn.c er_lgamma.c 	e_log.c e_log10.c e_pow.c e_rem_pio2.c e_remainder.c 	e_scalb.c e_sinh.c e_sqrt.c 	w_acos.c w_acosh.c w_asin.c w_atan2.c 	w_atanh.c w_cosh.c w_exp.c w_fmod.c 	w_gamma.c wr_gamma.c w_hypot.c w_j0.c 	w_j1.c w_jn.c w_lgamma.c wr_lgamma.c 	w_log.c w_log10.c w_pow.c w_remainder.c 	w_scalb.c w_sinh.c w_sqrt.c 	w_sincos.c 	w_cabs.c w_drem.c 	s_asinh.c s_atan.c s_ceil.c 	s_cos.c s_erf.c s_fabs.c s_floor.c 	s_frexp.c s_isnan.c s_ldexp.c 	s_signif.c s_sin.c 	s_tan.c s_tanh.c 	s_isinf.c s_infconst.c 	w_exp2.c w_tgamma.c


fsrc = kf_rem_pio2.c 	kf_cos.c kf_sin.c kf_tan.c 	ef_acos.c ef_acosh.c ef_asin.c ef_atan2.c 	ef_atanh.c ef_cosh.c ef_exp.c ef_fmod.c 	erf_gamma.c ef_hypot.c ef_j0.c 	ef_j1.c ef_jn.c erf_lgamma.c 	ef_log.c ef_log10.c ef_pow.c ef_rem_pio2.c ef_remainder.c 	ef_scalb.c ef_sinh.c ef_sqrt.c 	wf_acos.c wf_acosh.c wf_asin.c wf_atan2.c 	wf_atanh.c wf_cosh.c wf_exp.c wf_fmod.c 	wf_gamma.c wrf_gamma.c wf_hypot.c wf_j0.c 	wf_j1.c wf_jn.c wf_lgamma.c wrf_lgamma.c 	wf_log.c wf_log10.c wf_pow.c wf_remainder.c 	wf_scalb.c wf_sinh.c wf_sqrt.c 	wf_sincos.c 	wf_cabs.c wf_drem.c 	sf_asinh.c sf_atan.c sf_ceil.c 	sf_cos.c sf_erf.c sf_fabs.c sf_floor.c 	sf_frexp.c sf_isnan.c sf_ldexp.c 	sf_signif.c sf_sin.c 	sf_tan.c sf_tanh.c 	sf_isinf.c 	wf_exp2.c wf_tgamma.c


libmath_la_LDFLAGS = -Xcompiler -nostdlib

#noinst_LTLIBRARIES = libmath.la
#libmath_la_SOURCES = $(src) $(fsrc)
#noinst_DATA = objectlist.awk.in
noinst_DATA = 
noinst_LIBRARIES = lib.a
lib_a_SOURCES = $(src) $(fsrc)

chobj = wacos.def wacosh.def wasin.def sasinh.def 	satan.def watan2.def watanh.def wj0.def 	wcosh.def serf.def wexp.def 	sfabs.def sfloor.def wfmod.def sfrexp.def 	wgamma.def whypot.def sldexp.def wlog.def 	wlog10.def 	wpow.def wremainder.def ssin.def wsinh.def 	wsqrt.def stan.def stanh.def 	sisnan.def


SUFFIXES = .def

CHEW = ../../doc/makedoc -f $(srcdir)/../../doc/doc.str

TARGETDOC = ../tmp.texi

CLEANFILES = $(chobj) *.ref
mkinstalldirs = $(SHELL) $(top_srcdir)/../../mkinstalldirs
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(noinst_LIBRARIES)


DEFS =  -DPACKAGE=\"newlib\" -DVERSION=\"1.12.0\"  -I. -I$(srcdir) 
CPPFLAGS = -O2 -g -O2
LIBS = 
lib_a_LIBADD = 
lib_a_OBJECTS =  k_standard.$(OBJEXT) \
k_rem_pio2.$(OBJEXT) k_cos.$(OBJEXT) k_sin.$(OBJEXT) \
k_tan.$(OBJEXT) e_acos.$(OBJEXT) e_acosh.$(OBJEXT) \
e_asin.$(OBJEXT) e_atan2.$(OBJEXT) e_atanh.$(OBJEXT) \
e_cosh.$(OBJEXT) e_exp.$(OBJEXT) e_fmod.$(OBJEXT) \
er_gamma.$(OBJEXT) e_hypot.$(OBJEXT) e_j0.$(OBJEXT) \
e_j1.$(OBJEXT) e_jn.$(OBJEXT) er_lgamma.$(OBJEXT) \
e_log.$(OBJEXT) e_log10.$(OBJEXT) e_pow.$(OBJEXT) \
e_rem_pio2.$(OBJEXT) e_remainder.$(OBJEXT) \
e_scalb.$(OBJEXT) e_sinh.$(OBJEXT) e_sqrt.$(OBJEXT) \
w_acos.$(OBJEXT) w_acosh.$(OBJEXT) w_asin.$(OBJEXT) \
w_atan2.$(OBJEXT) w_atanh.$(OBJEXT) w_cosh.$(OBJEXT) \
w_exp.$(OBJEXT) w_fmod.$(OBJEXT) w_gamma.$(OBJEXT) \
wr_gamma.$(OBJEXT) w_hypot.$(OBJEXT) w_j0.$(OBJEXT) \
w_j1.$(OBJEXT) w_jn.$(OBJEXT) w_lgamma.$(OBJEXT) \
wr_lgamma.$(OBJEXT) w_log.$(OBJEXT) \
w_log10.$(OBJEXT) w_pow.$(OBJEXT) \
w_remainder.$(OBJEXT) w_scalb.$(OBJEXT) \
w_sinh.$(OBJEXT) w_sqrt.$(OBJEXT) w_sincos.$(OBJEXT) \
w_cabs.$(OBJEXT) w_drem.$(OBJEXT) s_asinh.$(OBJEXT) \
s_atan.$(OBJEXT) s_ceil.$(OBJEXT) s_cos.$(OBJEXT) \
s_erf.$(OBJEXT) s_fabs.$(OBJEXT) s_floor.$(OBJEXT) \
s_frexp.$(OBJEXT) s_isnan.$(OBJEXT) \
s_ldexp.$(OBJEXT) s_signif.$(OBJEXT) s_sin.$(OBJEXT) \
s_tan.$(OBJEXT) s_tanh.$(OBJEXT) s_isinf.$(OBJEXT) \
s_infconst.$(OBJEXT) w_exp2.$(OBJEXT) \
w_tgamma.$(OBJEXT) kf_rem_pio2.$(OBJEXT) \
kf_cos.$(OBJEXT) kf_sin.$(OBJEXT) kf_tan.$(OBJEXT) \
ef_acos.$(OBJEXT) ef_acosh.$(OBJEXT) \
ef_asin.$(OBJEXT) ef_atan2.$(OBJEXT) \
ef_atanh.$(OBJEXT) ef_cosh.$(OBJEXT) \
ef_exp.$(OBJEXT) ef_fmod.$(OBJEXT) \
erf_gamma.$(OBJEXT) ef_hypot.$(OBJEXT) \
ef_j0.$(OBJEXT) ef_j1.$(OBJEXT) ef_jn.$(OBJEXT) \
erf_lgamma.$(OBJEXT) ef_log.$(OBJEXT) \
ef_log10.$(OBJEXT) ef_pow.$(OBJEXT) \
ef_rem_pio2.$(OBJEXT) ef_remainder.$(OBJEXT) \
ef_scalb.$(OBJEXT) ef_sinh.$(OBJEXT) \
ef_sqrt.$(OBJEXT) wf_acos.$(OBJEXT) \
wf_acosh.$(OBJEXT) wf_asin.$(OBJEXT) \
wf_atan2.$(OBJEXT) wf_atanh.$(OBJEXT) \
wf_cosh.$(OBJEXT) wf_exp.$(OBJEXT) wf_fmod.$(OBJEXT) \
wf_gamma.$(OBJEXT) wrf_gamma.$(OBJEXT) \
wf_hypot.$(OBJEXT) wf_j0.$(OBJEXT) wf_j1.$(OBJEXT) \
wf_jn.$(OBJEXT) wf_lgamma.$(OBJEXT) \
wrf_lgamma.$(OBJEXT) wf_log.$(OBJEXT) \
wf_log10.$(OBJEXT) wf_pow.$(OBJEXT) \
wf_remainder.$(OBJEXT) wf_scalb.$(OBJEXT) \
wf_sinh.$(OBJEXT) wf_sqrt.$(OBJEXT) \
wf_sincos.$(OBJEXT) wf_cabs.$(OBJEXT) \
wf_drem.$(OBJEXT) sf_asinh.$(OBJEXT) \
sf_atan.$(OBJEXT) sf_ceil.$(OBJEXT) sf_cos.$(OBJEXT) \
sf_erf.$(OBJEXT) sf_fabs.$(OBJEXT) \
sf_floor.$(OBJEXT) sf_frexp.$(OBJEXT) \
sf_isnan.$(OBJEXT) sf_ldexp.$(OBJEXT) \
sf_signif.$(OBJEXT) sf_sin.$(OBJEXT) \
sf_tan.$(OBJEXT) sf_tanh.$(OBJEXT) \
sf_isinf.$(OBJEXT) wf_exp2.$(OBJEXT) \
wf_tgamma.$(OBJEXT)
LTLIBRARIES =  $(noinst_LTLIBRARIES)

libmath_la_LIBADD = 
#libmath_la_OBJECTS =  k_standard.lo k_rem_pio2.lo \
#k_cos.lo k_sin.lo k_tan.lo e_acos.lo e_acosh.lo \
#e_asin.lo e_atan2.lo e_atanh.lo e_cosh.lo e_exp.lo \
#e_fmod.lo er_gamma.lo e_hypot.lo e_j0.lo e_j1.lo \
#e_jn.lo er_lgamma.lo e_log.lo e_log10.lo e_pow.lo \
#e_rem_pio2.lo e_remainder.lo e_scalb.lo e_sinh.lo \
#e_sqrt.lo w_acos.lo w_acosh.lo w_asin.lo w_atan2.lo \
#w_atanh.lo w_cosh.lo w_exp.lo w_fmod.lo w_gamma.lo \
#wr_gamma.lo w_hypot.lo w_j0.lo w_j1.lo w_jn.lo \
#w_lgamma.lo wr_lgamma.lo w_log.lo w_log10.lo w_pow.lo \
#w_remainder.lo w_scalb.lo w_sinh.lo w_sqrt.lo \
#w_sincos.lo w_cabs.lo w_drem.lo s_asinh.lo s_atan.lo \
#s_ceil.lo s_cos.lo s_erf.lo s_fabs.lo s_floor.lo \
#s_frexp.lo s_isnan.lo s_ldexp.lo s_signif.lo s_sin.lo \
#s_tan.lo s_tanh.lo s_isinf.lo s_infconst.lo w_exp2.lo \
#w_tgamma.lo kf_rem_pio2.lo kf_cos.lo kf_sin.lo \
#kf_tan.lo ef_acos.lo ef_acosh.lo ef_asin.lo \
#ef_atan2.lo ef_atanh.lo ef_cosh.lo ef_exp.lo \
#ef_fmod.lo erf_gamma.lo ef_hypot.lo ef_j0.lo ef_j1.lo \
#ef_jn.lo erf_lgamma.lo ef_log.lo ef_log10.lo \
#ef_pow.lo ef_rem_pio2.lo ef_remainder.lo ef_scalb.lo \
#ef_sinh.lo ef_sqrt.lo wf_acos.lo wf_acosh.lo \
#wf_asin.lo wf_atan2.lo wf_atanh.lo wf_cosh.lo \
#wf_exp.lo wf_fmod.lo wf_gamma.lo wrf_gamma.lo \
#wf_hypot.lo wf_j0.lo wf_j1.lo wf_jn.lo wf_lgamma.lo \
#wrf_lgamma.lo wf_log.lo wf_log10.lo wf_pow.lo \
#wf_remainder.lo wf_scalb.lo wf_sinh.lo wf_sqrt.lo \
#wf_sincos.lo wf_cabs.lo wf_drem.lo sf_asinh.lo \
#sf_atan.lo sf_ceil.lo sf_cos.lo sf_erf.lo sf_fabs.lo \
#sf_floor.lo sf_frexp.lo sf_isnan.lo sf_ldexp.lo \
#sf_signif.lo sf_sin.lo sf_tan.lo sf_tanh.lo \
#sf_isinf.lo wf_exp2.lo wf_tgamma.lo
CFLAGS = -O2 -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
DATA =  $(noinst_DATA)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(lib_a_SOURCES) $(libmath_la_SOURCES)
OBJECTS = $(lib_a_OBJECTS) $(libmath_la_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .def .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(srcdir)/../../Makefile.shared
	cd $(top_srcdir) && $(AUTOMAKE) --cygnus math/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLIBRARIES:

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

distclean-noinstLIBRARIES:

maintainer-clean-noinstLIBRARIES:

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

lib.a: $(lib_a_OBJECTS) $(lib_a_DEPENDENCIES)
	-rm -f lib.a
	$(AR) cru lib.a $(lib_a_OBJECTS) $(lib_a_LIBADD)
	$(RANLIB) lib.a

mostlyclean-noinstLTLIBRARIES:

clean-noinstLTLIBRARIES:
	-test -z "$(noinst_LTLIBRARIES)" || rm -f $(noinst_LTLIBRARIES)

distclean-noinstLTLIBRARIES:

maintainer-clean-noinstLTLIBRARIES:

libmath.la: $(libmath_la_OBJECTS) $(libmath_la_DEPENDENCIES)
	$(LINK)  $(libmath_la_LDFLAGS) $(libmath_la_OBJECTS) $(libmath_la_LIBADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = math

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am:
check: check-am
installcheck-am:
installcheck: installcheck-am
install-info-am: 
install-info: install-info-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(LTLIBRARIES) $(DATA)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
		mostlyclean-libtool mostlyclean-noinstLTLIBRARIES \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstLIBRARIES clean-compile clean-libtool \
		clean-noinstLTLIBRARIES clean-tags clean-generic \
		mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstLIBRARIES distclean-compile \
		distclean-libtool distclean-noinstLTLIBRARIES \
		distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-noinstLTLIBRARIES \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool mostlyclean-noinstLTLIBRARIES \
distclean-noinstLTLIBRARIES clean-noinstLTLIBRARIES \
maintainer-clean-noinstLTLIBRARIES tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir info-am info dvi-am dvi check \
check-am installcheck-am installcheck install-info-am install-info \
install-exec-am install-exec install-data-am install-data install-am \
install uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


objectlist.awk.in: $(noinst_LTLIBRARIES)
	-rm -f objectlist.awk.in
	for i in `ls *.lo` ; \
	do \
	  echo $$i `pwd`/$$i >> objectlist.awk.in ; \
	done

.c.def:
	$(CHEW) < $< > $*.def 2> $*.ref
	touch stmp-def

doc: $(chobj)
	cat $(srcdir)/math.tex >> $(TARGETDOC)

# Texinfo does not appear to support underscores in file names, so we
# name the .def files without underscores.

wacos.def: w_acos.c
	$(CHEW) < $(srcdir)/w_acos.c >$@ 2>/dev/null
	touch stmp-def
wacosh.def: w_acosh.c
	$(CHEW) < $(srcdir)/w_acosh.c >$@ 2>/dev/null
	touch stmp-def
wasin.def: w_asin.c
	$(CHEW) < $(srcdir)/w_asin.c >$@ 2>/dev/null
	touch stmp-def
sasinh.def: s_asinh.c
	$(CHEW) < $(srcdir)/s_asinh.c >$@ 2>/dev/null
	touch stmp-def
satan.def: s_atan.c
	$(CHEW) < $(srcdir)/s_atan.c >$@ 2>/dev/null
	touch stmp-def
watan2.def: w_atan2.c
	$(CHEW) < $(srcdir)/w_atan2.c >$@ 2>/dev/null
	touch stmp-def
watanh.def: w_atanh.c
	$(CHEW) < $(srcdir)/w_atanh.c >$@ 2>/dev/null
	touch stmp-def
wj0.def: w_j0.c
	$(CHEW) < $(srcdir)/w_j0.c >$@ 2>/dev/null
	touch stmp-def
scopysign.def: s_copysign.c
	$(CHEW) < $(srcdir)/../common/s_copysign.c >$@ 2>/dev/null
	touch stmp-def
wcosh.def: w_cosh.c
	$(CHEW) < $(srcdir)/w_cosh.c >$@ 2>/dev/null
	touch stmp-def
serf.def: s_erf.c
	$(CHEW) < $(srcdir)/s_erf.c >$@ 2>/dev/null
	touch stmp-def
wexp.def: w_exp.c
	$(CHEW) < $(srcdir)/w_exp.c >$@ 2>/dev/null
	touch stmp-def
sfabs.def: s_fabs.c
	$(CHEW) < $(srcdir)/s_fabs.c >$@ 2>/dev/null
	touch stmp-def
sfloor.def: s_floor.c
	$(CHEW) < $(srcdir)/s_floor.c >$@ 2>/dev/null
	touch stmp-def
wfmod.def: w_fmod.c
	$(CHEW) < $(srcdir)/w_fmod.c >$@ 2>/dev/null
	touch stmp-def
sfrexp.def: s_frexp.c
	$(CHEW) < $(srcdir)/s_frexp.c >$@ 2>/dev/null
	touch stmp-def
wgamma.def: w_gamma.c
	$(CHEW) < $(srcdir)/w_gamma.c >$@ 2>/dev/null
	touch stmp-def
whypot.def: w_hypot.c
	$(CHEW) < $(srcdir)/w_hypot.c >$@ 2>/dev/null
	touch stmp-def
sldexp.def: s_ldexp.c
	$(CHEW) < $(srcdir)/s_ldexp.c >$@ 2>/dev/null
	touch stmp-def
wlog.def: w_log.c
	$(CHEW) < $(srcdir)/w_log.c >$@ 2>/dev/null
	touch stmp-def
wlog10.def: w_log10.c
	$(CHEW) < $(srcdir)/w_log10.c >$@ 2>/dev/null
	touch stmp-def
wpow.def: w_pow.c
	$(CHEW) < $(srcdir)/w_pow.c >$@ 2>/dev/null
	touch stmp-def
wremainder.def: w_remainder.c
	$(CHEW) < $(srcdir)/w_remainder.c >$@ 2>/dev/null
	touch stmp-def
ssin.def: s_sin.c
	$(CHEW) < $(srcdir)/s_sin.c >$@ 2>/dev/null
	touch stmp-def
wsinh.def: w_sinh.c
	$(CHEW) < $(srcdir)/w_sinh.c >$@ 2>/dev/null
	touch stmp-def
wsqrt.def: w_sqrt.c
	$(CHEW) < $(srcdir)/w_sqrt.c >$@ 2>/dev/null
	touch stmp-def
stan.def: s_tan.c
	$(CHEW) < $(srcdir)/s_tan.c >$@ 2>/dev/null
	touch stmp-def
stanh.def: s_tanh.c
	$(CHEW) < $(srcdir)/s_tanh.c >$@ 2>/dev/null
	touch stmp-def
sisnan.def: s_isnan.c
	$(CHEW) < $(srcdir)/s_isnan.c >$@ 2>/dev/null
	touch stmp-def

# A partial dependency list.

$(lib_a_OBJECTS): $(srcdir)/../../libc/include/math.h $(srcdir)/../common/fdlibm.h

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
